backend:
  name: github
  repo: roedwin-afk/landing_panelparacuartofrio
  branch: main

media_folder: "src/assets/images"
public_folder: "/src/assets/images"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Publish Date", name: "pubDate", widget: "datetime" }
      - { label: "Featured Image", name: "heroImage", widget: "image", required: false }
      - { label: "Draft", name: "draft", widget: "boolean", default: false, required: false }
      - { label: "Body", name: "body", widget: "markdown" }